/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrazosPagamentoRouteImport } from './routes/prazos-pagamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GlosaRecuperadaRouteImport } from './routes/glosa-recuperada'
import { Route as GlosaRankingRouteImport } from './routes/glosa-ranking'
import { Route as GlosaMotivosRouteImport } from './routes/glosa-motivos'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as CbhpmRouteImport } from './routes/cbhpm'
import { Route as AgendasPositivasRouteImport } from './routes/agendas-positivas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrazosPagamentoRoute = PrazosPagamentoRouteImport.update({
  id: '/prazos-pagamento',
  path: '/prazos-pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosaRecuperadaRoute = GlosaRecuperadaRouteImport.update({
  id: '/glosa-recuperada',
  path: '/glosa-recuperada',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosaRankingRoute = GlosaRankingRouteImport.update({
  id: '/glosa-ranking',
  path: '/glosa-ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosaMotivosRoute = GlosaMotivosRouteImport.update({
  id: '/glosa-motivos',
  path: '/glosa-motivos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const CbhpmRoute = CbhpmRouteImport.update({
  id: '/cbhpm',
  path: '/cbhpm',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendasPositivasRoute = AgendasPositivasRouteImport.update({
  id: '/agendas-positivas',
  path: '/agendas-positivas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agendas-positivas': typeof AgendasPositivasRoute
  '/cbhpm': typeof CbhpmRoute
  '/dashboards': typeof DashboardsRoute
  '/export': typeof ExportRoute
  '/glosa-motivos': typeof GlosaMotivosRoute
  '/glosa-ranking': typeof GlosaRankingRoute
  '/glosa-recuperada': typeof GlosaRecuperadaRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/prazos-pagamento': typeof PrazosPagamentoRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agendas-positivas': typeof AgendasPositivasRoute
  '/cbhpm': typeof CbhpmRoute
  '/dashboards': typeof DashboardsRoute
  '/export': typeof ExportRoute
  '/glosa-motivos': typeof GlosaMotivosRoute
  '/glosa-ranking': typeof GlosaRankingRoute
  '/glosa-recuperada': typeof GlosaRecuperadaRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/prazos-pagamento': typeof PrazosPagamentoRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agendas-positivas': typeof AgendasPositivasRoute
  '/cbhpm': typeof CbhpmRoute
  '/dashboards': typeof DashboardsRoute
  '/export': typeof ExportRoute
  '/glosa-motivos': typeof GlosaMotivosRoute
  '/glosa-ranking': typeof GlosaRankingRoute
  '/glosa-recuperada': typeof GlosaRecuperadaRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/prazos-pagamento': typeof PrazosPagamentoRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendas-positivas'
    | '/cbhpm'
    | '/dashboards'
    | '/export'
    | '/glosa-motivos'
    | '/glosa-ranking'
    | '/glosa-recuperada'
    | '/home'
    | '/login'
    | '/prazos-pagamento'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agendas-positivas'
    | '/cbhpm'
    | '/dashboards'
    | '/export'
    | '/glosa-motivos'
    | '/glosa-ranking'
    | '/glosa-recuperada'
    | '/home'
    | '/login'
    | '/prazos-pagamento'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendas-positivas'
    | '/cbhpm'
    | '/dashboards'
    | '/export'
    | '/glosa-motivos'
    | '/glosa-ranking'
    | '/glosa-recuperada'
    | '/home'
    | '/login'
    | '/prazos-pagamento'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendasPositivasRoute: typeof AgendasPositivasRoute
  CbhpmRoute: typeof CbhpmRoute
  DashboardsRoute: typeof DashboardsRoute
  ExportRoute: typeof ExportRoute
  GlosaMotivosRoute: typeof GlosaMotivosRoute
  GlosaRankingRoute: typeof GlosaRankingRoute
  GlosaRecuperadaRoute: typeof GlosaRecuperadaRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PrazosPagamentoRoute: typeof PrazosPagamentoRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prazos-pagamento': {
      id: '/prazos-pagamento'
      path: '/prazos-pagamento'
      fullPath: '/prazos-pagamento'
      preLoaderRoute: typeof PrazosPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosa-recuperada': {
      id: '/glosa-recuperada'
      path: '/glosa-recuperada'
      fullPath: '/glosa-recuperada'
      preLoaderRoute: typeof GlosaRecuperadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosa-ranking': {
      id: '/glosa-ranking'
      path: '/glosa-ranking'
      fullPath: '/glosa-ranking'
      preLoaderRoute: typeof GlosaRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosa-motivos': {
      id: '/glosa-motivos'
      path: '/glosa-motivos'
      fullPath: '/glosa-motivos'
      preLoaderRoute: typeof GlosaMotivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbhpm': {
      id: '/cbhpm'
      path: '/cbhpm'
      fullPath: '/cbhpm'
      preLoaderRoute: typeof CbhpmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendas-positivas': {
      id: '/agendas-positivas'
      path: '/agendas-positivas'
      fullPath: '/agendas-positivas'
      preLoaderRoute: typeof AgendasPositivasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendasPositivasRoute: AgendasPositivasRoute,
  CbhpmRoute: CbhpmRoute,
  DashboardsRoute: DashboardsRoute,
  ExportRoute: ExportRoute,
  GlosaMotivosRoute: GlosaMotivosRoute,
  GlosaRankingRoute: GlosaRankingRoute,
  GlosaRecuperadaRoute: GlosaRecuperadaRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PrazosPagamentoRoute: PrazosPagamentoRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
