-- Create api_zg_item table mirroring the Zero Glosa API V2 JSON payload.
-- Numeric fields use numeric, clearly-ISO datetime fields use timestamptz,
-- mixed/empty/dd-mm-yyyy date fields stay as text to avoid parse errors,
-- and ids/strings are text. Column names longer than 63 chars are truncated.

CREATE TABLE public.api_zg_item (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  import_id uuid,
  raw jsonb,
  ingested_at timestamptz NOT NULL DEFAULT now(),

  -- chaves de unicidade
  cliente_id text,
  entidade_id text,

  -- campos textuais / identificadores
  apos_inicio_pdt text,
  cc_1_analise_mes_vencimento_recurso text,
  cc_data_analise_glosa text,
  cc_i_aceite_data text,
  cc_i_item_data_execucao text,
  cc_i_motivos_glosa_descricoes text,
  cc_i_motivos_glosa_primeira_descricao text,
  cc_i_motivos_glosa_primeiro_codigo text,
  cc_i_recurso_data text,
  cc_mes_pagamento text,
  cc_situacao_envio_recurso text,
  cliente_grupo text,
  cliente_nome text,
  competencia_descricao text,
  convenio_is_lancamento_manual text,
  convenio_nome text,
  convenio_tipo_pagamento text,
  data_envio_recurso text,
  f_nota_fiscal_eletronica_numero text,
  f_nota_fiscal_numero text,
  f_remessa_fechada text,
  f_remessa_titulo text,
  g_competencia_conv_descricao text,
  g_entidade_id text,
  g_guia_associada text,
  g_guia_atendente_id text,
  g_guia_atendente_id_unidade_coletiva text,
  g_guia_atendente_identificador_erp text,
  g_guia_atendente_nome text,
  g_guia_atendente_nome_unidade_coletiva text,
  g_guia_beneficiario_matricula text,
  g_guia_beneficiario_nome text,
  g_guia_beneficiario_plano text,
  g_guia_codigo_prestador text,
  g_guia_convenio_numero_guia text,
  g_guia_convenio_situacaoguia text,
  g_guia_data_referencia text,
  g_guia_data_referencia_lote text,
  g_guia_discriminador text,
  g_guia_eh_recurso text,
  g_guia_glosa_total text,
  g_guia_mudanca_status_analise_data text,
  g_guia_numero_atendimento text,
  g_guia_numero_conta text,
  g_guia_operadora_original text,
  g_guia_prestador_original text,
  g_guia_senha text,
  g_guia_status_analise text,
  g_guia_status_conciliacao text,
  g_guia_tipo text,
  g_recurso_data_envio text,
  g_recurso_data_pagamento text,
  g_recurso_data_vencimento text,
  g_recurso_protocolo text,
  hospital_alias text,
  hospital_cnpj text,
  hospital_nome text,
  hospital_reg text,
  i_aceite_data text,
  i_aceite_justificativa text,
  i_aceite_usuario_realizou_nome_completo text,
  i_categoria_motivos_glosa_nome text,
  i_dados_assoc_usuario_e_zeroglosa text,
  i_dados_assoc_usuario_nome_completo text,
  i_demais_recursos_valor_total text,
  i_item_agrupador_envio text,
  i_item_assoc_manual_auto text,
  i_item_categoria text,
  i_item_centro_custos_codigo text,
  i_item_centro_custos_descricao text,
  i_item_codigo_no_sistema text,
  i_item_comentario_aceite text,
  i_item_convenio_descricao text,
  i_item_data_analise_glosa text,
  i_item_descricao text,
  i_item_executante_crm text,
  i_item_executante_nome text,
  i_item_grau_participacao text,
  i_item_numero_conta text,
  i_item_solicitante_nome text,
  i_item_tipo_de_glosa_descricao text,
  i_item_tipo_tabela text,
  i_justificativa_interna_codigo text,
  i_justificativa_interna_descricao text,
  i_justificativa_interna_id text,
  i_motivos_glosa_codigos text,
  i_motivos_glosa_complementos text,
  i_motivos_tiss_codigos text,
  i_motivos_tiss_descricoes text,
  i_recurso_data text,
  i_recurso_data_envio text,
  i_recurso_envio_usuario text,
  i_recurso_justificativa text,
  i_recurso_justificativa_interna_codigo text,
  i_recurso_justificativa_interna_descricao text,
  i_recurso_justificativa_interna_id text,
  i_recurso_motivo_glosa_descricao_ultimo_recurso text,
  i_recurso_protocolo text,
  i_recurso_usuario_nome_completo text,
  i_recurso_valor_glosa_mantida text,
  i_refaturamento_justificativa text,
  i_ultimo_recurso_aceite_usuario text,
  i_ultimo_recurso_codigo_glosa text,
  i_ultimo_recurso_complemento_de_glosa text,
  i_ultimo_recurso_descricao_glosa text,
  i_ultimo_recurso_justificativa_aceite text,
  i_ultimo_recurso_justificativa_recurso text,
  i_ultimo_recurso_tipo_de_glosa text,
  i_ultimo_recurso_tipo_de_glosa_id text,
  i_ultimo_recurso_usuario text,
  mes_emissao text,
  mes_emissao_nota_fiscal text,
  mes_vencimento text,
  operadora_codigo text,
  operadora_grupo text,
  operadora_nome text,
  sistema_de_gestao_categorias text,
  sistema_de_gestao_nome text,

  -- datetimes ISO
  f_nota_fiscal_data_emissao timestamptz,
  f_nota_fiscal_data_vencimento timestamptz,
  f_nota_fiscal_remessa_data_vencimento timestamptz,
  f_remessa_data_emissao timestamptz,
  f_remessa_data_entrega timestamptz,
  f_remessa_data_envio timestamptz,
  f_remessa_data_vencimento timestamptz,
  g_guia_data_atendimento timestamptz,
  g_guia_data_emissao timestamptz,
  g_guia_data_pagamento timestamptz,
  g_guia_data_saida timestamptz,
  g_guia_mudanca_status_conciliacao_data timestamptz,
  g_guia_prazo_envio_recurso timestamptz,
  g_guia_submissao_para_analise_data timestamptz,
  i_dados_assoc_data timestamptz,
  i_item_data_execucao timestamptz,
  i_ultimo_recurso_data_pagamento timestamptz,
  r_recebimento_data_recebimento timestamptz,
  ultima_atualizacao timestamptz,

  -- numéricos
  cc_1_analise_i_recurso_valor_recebido numeric,
  cc_aceite_devolucao numeric,
  cc_i_item_1_analise_pendente_retorno numeric,
  cc_i_item_percentual_diferenca numeric,
  cc_i_item_percentual_glosa_submetida numeric,
  cc_i_item_soma_analises_glosa_atual numeric,
  cc_i_item_soma_analises_percentual_saldo_final_de_glosa_submeti numeric,
  cc_i_item_soma_analises_recurso_recuperado numeric,
  cc_item_soma_analises_saldo_final_de_glosa_submetida numeric,
  cc_reanalises_demais_recursos_valor_aceito numeric,
  cc_reanalises_i_demais_recursos_valor_em_aberto numeric,
  cc_reanalises_i_demais_recursos_valor_recebido numeric,
  cc_soma_analises_i_ultimo_recurso_valor_glosa_mantida numeric,
  cc_usuario_analise_glosa numeric,
  cc_valor_analisado numeric,
  f_remessa_numero numeric,
  f_remessa_protocolo_envio numeric,
  g_guia_ngprest numeric,
  g_guia_numero_demonstrativo numeric,
  g_guia_numero_guia numeric,
  g_guia_numero_lote numeric,
  g_guia_numero_processo_complementar text,
  g_guia_numero_protocolo numeric,
  g_guia_qtd_dias_para_enviar_recurso numeric,
  g_guia_valor_cobrado numeric,
  g_guia_valor_glosa_inicial numeric,
  g_guia_valor_recebido numeric,
  g_recurso_idx numeric,
  g_recurso_valor_recebido numeric,
  i_aceite_valor numeric,
  i_aceite_valor_produtividade numeric,
  i_demais_recursos_qtd numeric,
  i_demais_recursos_valor_glosa_em_analise numeric,
  i_divergencia_valor_importado numeric,
  i_item_codigo numeric,
  i_item_convenio_codigo numeric,
  i_item_qtd_cobrada numeric,
  i_item_qtd_recebida numeric,
  i_item_saldo_glosa numeric,
  i_item_sequencial_item numeric,
  i_item_solicitante_crm numeric,
  i_item_valor_apresentado numeric,
  i_item_valor_cobrado numeric,
  i_item_valor_diferenca numeric,
  i_item_valor_glosa numeric,
  i_item_valor_glosa_em_analise numeric,
  i_item_valor_recebido numeric,
  i_item_valor_unitario_cobrado numeric,
  i_item_valor_unitario_recebido numeric,
  i_recurso_idx numeric,
  i_recurso_valor numeric,
  i_recurso_valor_glosa_em_analise numeric,
  i_recurso_valor_produtividade numeric,
  i_refaturamento_valor numeric,
  i_total_recurso_valor_recebido numeric,
  i_total_valor_aceito numeric,
  i_total_valor_glosa_em_analise numeric,
  i_ultimo_recurso_valor_aceite numeric,
  i_ultimo_recurso_valor_glosa_mantida numeric,
  i_ultimo_recurso_valor_recurso numeric,
  i_ultimo_recurso_valor_total numeric,
  operadora_ans_registro_ans numeric,
  operadora_registro_ans numeric,
  percentual_glosa_item_sobre_glosa_total numeric,

  CONSTRAINT api_zg_item_cliente_entidade_unique UNIQUE (cliente_id, entidade_id)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.api_zg_item TO authenticated;
GRANT ALL ON public.api_zg_item TO service_role;

ALTER TABLE public.api_zg_item ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage api_zg_item"
ON public.api_zg_item
FOR ALL
TO authenticated
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE INDEX api_zg_item_import_id_idx ON public.api_zg_item (import_id);
CREATE INDEX api_zg_item_ultima_atualizacao_idx ON public.api_zg_item (ultima_atualizacao);

CREATE OR REPLACE FUNCTION public.get_api_zg_item_columns()
RETURNS SETOF text
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = public, information_schema
AS $$
  SELECT column_name::text
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'api_zg_item';
$$;