ALTER TABLE public.glosa_records
  ADD COLUMN IF NOT EXISTS "Nome do Convenio" text,
  ADD COLUMN IF NOT EXISTS "Data Pagto." date,
  ADD COLUMN IF NOT EXISTS "Mês Pgto." text,
  ADD COLUMN IF NOT EXISTS "Tipo de Guia" text,
  ADD COLUMN IF NOT EXISTS "Nome paciente" text,
  ADD COLUMN IF NOT EXISTS "Num. Conta" text,
  ADD COLUMN IF NOT EXISTS "Dt.Atendimento" date,
  ADD COLUMN IF NOT EXISTS "Data Saída Guia" date,
  ADD COLUMN IF NOT EXISTS "Status de Analise" text,
  ADD COLUMN IF NOT EXISTS "Data Analise" date,
  ADD COLUMN IF NOT EXISTS "Situação da Guia" text,
  ADD COLUMN IF NOT EXISTS "Discriminador Guia" text,
  ADD COLUMN IF NOT EXISTS "Guia é de Recurso" text,
  ADD COLUMN IF NOT EXISTS "Conta Integralmente Glosada" text,
  ADD COLUMN IF NOT EXISTS "Nº Parcial de Recurso" numeric,
  ADD COLUMN IF NOT EXISTS "Nº Parcial do Item de Recurso" numeric,
  ADD COLUMN IF NOT EXISTS "Tipo produto" text,
  ADD COLUMN IF NOT EXISTS "Dt.Realizacao" date,
  ADD COLUMN IF NOT EXISTS "Dt. Recurso" date,
  ADD COLUMN IF NOT EXISTS "Dt.Aceite" date,
  ADD COLUMN IF NOT EXISTS "Centro de custos" text,
  ADD COLUMN IF NOT EXISTS "Apresentado (Demonstrativo)" numeric,
  ADD COLUMN IF NOT EXISTS "Qtde. Faturada" numeric,
  ADD COLUMN IF NOT EXISTS "Vlr. Unit. Faturado" numeric,
  ADD COLUMN IF NOT EXISTS "Valor Faturado" numeric,
  ADD COLUMN IF NOT EXISTS "Qtde. Paga" numeric,
  ADD COLUMN IF NOT EXISTS "Vlr. Unit. Pago" numeric,
  ADD COLUMN IF NOT EXISTS "Valor Pago" numeric,
  ADD COLUMN IF NOT EXISTS "Diferenca" numeric,
  ADD COLUMN IF NOT EXISTS "Glosa Submetida" numeric,
  ADD COLUMN IF NOT EXISTS "1ª Análise - Glosa Aceita" numeric,
  ADD COLUMN IF NOT EXISTS "1ª Análise - Glosa Refaturada" numeric,
  ADD COLUMN IF NOT EXISTS "1ª Análise - Glosa Recursada" numeric,
  ADD COLUMN IF NOT EXISTS "1ª Análise - Pendente Retorno" numeric,
  ADD COLUMN IF NOT EXISTS "1ª Análise - Glosa Recuperada" numeric,
  ADD COLUMN IF NOT EXISTS "1ª Análise - Glosa Mantida" numeric,
  ADD COLUMN IF NOT EXISTS "1ª Análise - Soma Aceites e Recursos" numeric,
  ADD COLUMN IF NOT EXISTS "Usuário Realizou Recurso" text,
  ADD COLUMN IF NOT EXISTS "Data Envio Recurso Lote" date,
  ADD COLUMN IF NOT EXISTS "Protocolo de Recurso Lote" text,
  ADD COLUMN IF NOT EXISTS "Usuário Realizou Aceite" text,
  ADD COLUMN IF NOT EXISTS "Data Envio Recurso Item" date,
  ADD COLUMN IF NOT EXISTS "Protocolo Envio Recurso Item" text,
  ADD COLUMN IF NOT EXISTS "Usuario Envio Recurso Item" text,
  ADD COLUMN IF NOT EXISTS "Usuário Realizou Refaturamento" text,
  ADD COLUMN IF NOT EXISTS "Data Refaturamento" date,
  ADD COLUMN IF NOT EXISTS "Usuario Analise" text,
  ADD COLUMN IF NOT EXISTS "Data última atualização dados" timestamp with time zone;