// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leyczouymuurmftqtonh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxleWN6b3V5bXV1cm1mdHF0b25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5OTQ5MjEsImV4cCI6MjA5NjU3MDkyMX0.XqpTqQb0t3qecp-2J94kR7IN9SCm6bMSs5Q6igHHOHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});